# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\file_title_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(844, 60)
        Frame.setMinimumSize(QtCore.QSize(0, 60))
        Frame.setMaximumSize(QtCore.QSize(16777215, 60))
        Frame.setStyleSheet("background-color:rgb(0, 85, 255);\n"
"border-radius: 15px;\n"
"color:white;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setContentsMargins(10, 10, 10, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_file = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_file.sizePolicy().hasHeightForWidth())
        self.label_file.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_file.setFont(font)
        self.label_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_file.setWordWrap(True)
        self.label_file.setObjectName("label_file")
        self.horizontalLayout.addWidget(self.label_file)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_file.setText(_translate("Frame", "Maktab"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
