# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\yondosh_word_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(844, 60)
        Frame.setMinimumSize(QtCore.QSize(0, 60))
        Frame.setMaximumSize(QtCore.QSize(16777215, 60))
        Frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_word_before = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_word_before.sizePolicy().hasHeightForWidth())
        self.label_word_before.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_word_before.setFont(font)
        self.label_word_before.setWordWrap(True)
        self.label_word_before.setObjectName("label_word_before")
        self.horizontalLayout.addWidget(self.label_word_before)
        self.label_word = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_word.sizePolicy().hasHeightForWidth())
        self.label_word.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_word.setFont(font)
        self.label_word.setWordWrap(True)
        self.label_word.setObjectName("label_word")
        self.horizontalLayout.addWidget(self.label_word)
        self.label_word_after = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_word_after.sizePolicy().hasHeightForWidth())
        self.label_word_after.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_word_after.setFont(font)
        self.label_word_after.setWordWrap(True)
        self.label_word_after.setObjectName("label_word_after")
        self.horizontalLayout.addWidget(self.label_word_after)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_word_before.setText(_translate("Frame", "marta ishlatilgan"))
        self.label_word.setText(_translate("Frame", "Maktab"))
        self.label_word_after.setText(_translate("Frame", "marta ishlatilgan"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
